version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgresql.conf:/etc/postgresql/16/main/postgresql.conf
    restart: always
    environment:    
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - transcendence_net
    ports:
      - "5432:5432"

  django:
    build: ./django_trans/
    volumes:
      - .django_trans:/usr/src/app
      - static_volume:/app/static
      - media_volume:/app/media
    command: gunicorn django_trans.wsgi:application --bind 0.0.0.0:8000
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - transcendence_net

  nginx:
      image: nginx:alpine
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/certs:/etc/nginx/certs:ro
        - static_volume:/usr/src/app/static
        - media_volume:/usr/src/app/media
      ports:
        - "443:443"
        - "80:80"
      depends_on:
        - django
      networks:
        - transcendence_net

  socketio-server:
    build: 
      context: ./socketio-server
    ports:
      - "3000:3000"
    volumes:
      - ./socketio-server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - transcendence_net

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  transcendence_net:
    driver: bridge
